### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by 183amir** [snwh/moka-icon-theme#175] opened 2015-04-10 11:35 UTC
Hi,

I just upgraded to Gnome 3.16 and I am seeing different icon sizes in my home folder in nautilus:
![screenshot from 2015-04-10 20-31-08](https://cloud.githubusercontent.com/assets/5738695/7086917/1369761c-dfc1-11e4-9099-8fa061f64cde.png)

This does not happen with the default icons (Adwaita).

**Comment by nyc** [comment] 2015-04-14 11:39
I can confirm the above bug. Also, dragging items onto a full-sized folder icon makes it shrink to the size of the smaller folders in the image above.

**Comment by dyskette** [comment] 2015-04-14 14:20
If you make the icons bigger, the desktop icon gets even bigger than the others.

![captura de pantalla de 2015-04-14 09-09-10](https://cloud.githubusercontent.com/assets/6687927/7138471/37d002d8-e286-11e4-984e-62e5571fd312.png)

Other icons like iso mimetype are also small.

![captura de pantalla de 2015-04-14 09-19-13](https://cloud.githubusercontent.com/assets/6687927/7138661/5ce30e66-e287-11e4-924a-7e581ad26893.png)

**Comment by snwh** [comment] 2015-04-14 23:57
I know. I've gotten around to GNOME 3.16 stuff for Moka

**Comment by vpooley** [comment] 2015-04-17 09:29
I see the same issue on Gnome 3.14.2;

![screenshot from 2015-04-17 10 23 35](https://cloud.githubusercontent.com/assets/10455243/7199420/9074ccee-e4ec-11e4-8aac-da37935d7eb4.png)

**Comment by vpooley** [comment] 2015-04-17 13:20
Just had a look at this myself and the small icons are from the Faba icon theme and the size difference of the folders is a limitation of Faba, not Moka.
The issue with the Faba icon theme is that 48x48 is the largest available size for most of the icons in the set and they are set to a fixed size in Faba's index.theme file whereas Faba has a different folder.svg for the other sizes. Changing Faba's index.theme so that all the 48x48 icons are scalable instead of fixed sorts out the size difference, they are all SVGs anyway so they scale cleanly to any size. But at larger sizes this causes the places icons to appear different to the available vanilla folder icons for that size due to the thicker scaled outlines.
![screenshot from 2015-04-17 14 02 38](https://cloud.githubusercontent.com/assets/10455243/7202534/335c139a-e50b-11e4-98f1-f10712d4e42d.png)
I can see this has been raised as an issue on the Faba repository so I'll repost this under that issue.

![screenshot from 2015-04-17 13 56 01](https://cloud.githubusercontent.com/assets/10455243/7202361/836c7e1c-e509-11e4-9429-0b84a6c8606d.png)

![screenshot from 2015-04-17 13 52 30](https://cloud.githubusercontent.com/assets/10455243/7202345/60a15f9c-e509-11e4-9b8f-b0e19e072564.png)

![screenshot from 2015-04-17 13 56 40](https://cloud.githubusercontent.com/assets/10455243/7202372/998d5f04-e509-11e4-9e8a-ca99fb1d5ac0.png)

There does remain this Moka issue when in Nautilus' icon view at a zoom level showing 64x64 icons, the Desktop icon shows at 96x96, at least on Gnome 3.14 most other zoom levels appear OK other than at max zoom where the 256x256 Desktop icon appears bigger than everything else.
I've tried amending Moka's index.theme file so that all non-scalables are of type 'Fixed' instead of 'Scalable' or 'Threshold'. I've checked that 64x64/places/user-desktop.png is in fact 64x64 pixels in size and it is and there doesn't seem to be an issue with the symlinks 64x64/places/desktop.png & 64x64/places/gnome-fs-desktop.png. I'm stumpted.

**Comment by vpooley** [comment] 2015-04-18 19:58
I'm new to theming but I'm keen on making these icons the default theme in the next release of [Chapeau](http://chapeaulinux.org) so I've spent a bit of time looking at this and I think I've figured what might be going wrong.
The problems are a combination of a few little issues to do with the index.theme file and a missing scalable icon set, but especially for Gnome 3.16 there needs to be a 128x128 set of icons if there's no scalables.
The index file declares that a set of scalable files are present under a 'scalable' directory but there isn't one, I suggest removing all refs to scalables from the theme file or adding a set of scalable vectors.

**Gnome 3.14**
I wanted to see if Gnome 3.14 used the 256x256 icons declared as the 'Scalable' type if other non-scalable sizes were missing, so I altered the size options to MinSize=56 MaxSize=512 for the 256x256 sets then changed all other sets to the type 'Fixed' instead of 'Threshold' or 'Scalable'. This didn't make a difference in Gnome 3.14.2 so it only seems to want to scale vector images in Nautilus, not PNG bitmaps.
![screenshot from 2015-04-18 20 53 57](https://cloud.githubusercontent.com/assets/10455243/7217022/3e1d2bc2-e60d-11e4-81db-fcc67984915c.png)

**Gnome 3.16**
Away from Gnome 3.14 the difference with Gnome 3.16 is that in earlier Gnome versions, Nautilus has 7 different zoom levels, 33%, 50%, 66%, 100%, 150%, 200%, 400% (as shown in Nautilus' preferences), in the Gnome schema *org.gnome.nautilus.icon-view.default-zoom-level* these are defined as 'smallest', 'smaller', 'small', 'normal', 'large', 'larger', 'largest'.
In Gnome 3.16 this has changed to only 3 zoom levels and Nautilus' preferences matches the schema values 'small', 'standard' & 'large', 'large' zooms the icons to 128x128. As there are no 128x128 bitmaps and no scalable vector images available the 256x256 is used instead giving you the giant Moka icons...
![screenshot from 2015-04-18 15-37-18](https://cloud.githubusercontent.com/assets/10455243/7216958/fb562f7a-e60a-11e4-95f7-8de125779721.png)
![screenshot from 2015-04-18 15-49-32](https://cloud.githubusercontent.com/assets/10455243/7217003/919b910e-e60c-11e4-8eb4-2d7edc1f0ffc.png)


I created a 128x128 icon set by copying the 256x256 set, resizing them with imagemagick and making the appropriate changes to the index.theme. This solves the Nautilus issue with Gnome 3.16.
![screenshot from 2015-04-18 20-41-14](https://cloud.githubusercontent.com/assets/10455243/7216964/63ea9620-e60b-11e4-8ad1-83c4aa444b8e.png)

@snwh I've pushed the changes to the master branch of my fork, there is an outstanding pull request. Let me know if you'd like me to make a new request or something.

Hope that helps.
Vin

**Comment by snwh** [comment] 2015-04-19 04:28
The problem is in Faba –the fact that there are several icons still not in the theme– and a temporary solution has been committed to the Faba repos. 

Despite being SVG they are **not** meant to scale beyond the size they are at.

**Comment by vpooley** [comment] 2015-04-19 05:47
Hi Sam, I know the Faba issue.
I'm on to the Moka issue with the oversized icons as described above. This happens with or without Faba.

**Comment by snwh** [comment] 2015-04-19 15:14
That's not an issue, you've enlarged the icons to that size in Files. If there were corresponding icons of that size in Faba they would also be that size –Faba doesn't have many 256x256 icons.

**Comment by vpooley** [comment] 2015-04-19 21:12
As explained, this is an issue whether the Faba icon is on the system or not, also as explained nautilus in Gnome 3.16 does not zoom as much as previous versions and the maximum zoom level tops out at 128x128.
Anyway I'll leave you to figure it out for yourself.

**Comment by snwh** [comment] 2015-04-19 23:16
Ahhh. I understand what you're getting at now. (You may have overexplained :wink: )

**Comment by vpooley** [comment] 2015-04-20 06:57
No worries, I have the solution as described above applied to [my fork](https://github.com/chapeaulinux/moka-icon-theme/commits/master) which is now 7 commits ahead. Shall I reopen my pull request?

**Comment by snwh** [comment] 2015-04-20 15:39
No, that's not the solution. Also I can see you've made unnecessary changes and additions to icons that I don't want.

**Comment by jandudulski** [comment] 2015-05-27 08:21
I just upgraded Fedora with a new Gnome and I'm suffering from this now. Any progress on this issue?

**Comment by jandudulski** [comment] 2015-06-23 15:07
@snwh or @vpooley - do you plan to work on this?

**Comment by vpooley** [comment] 2015-06-23 15:44
This isn't my project and Sam didn't like any of the above suggestions, in the meantime these issues have been addressed do some degree in my forks of moka and faba.
Try out the [master branch of the moka fork](https://github.com/chapeaulinux/moka-icon-theme) and the [chapeau branch of the faba fork](https://github.com/chapeaulinux/faba-icon-theme/tree/chapeau).

[Chapeau 22](http://chapeaulinux.org) now ships these icons as default.

**Closed** 2016-12-08 08:27 UTC
